// iben-genesis - Base-12 Radix Space Engine (WASM stub)
// This file is generated by wasm-pack during build
// For development/testing, import the actual generated files

import initWasm, { convert_to_base12, radix_range_iter, benchmark_conversion } from './iben_genesis.js';

let initialized = false;

export async function init() {
  if (!initialized) {
    await initWasm();
    initialized = true;
  }
  return {
    convert_to_base12,
    radix_range_iter,
    benchmark_conversion
  };
}

export async function toBase12(value) {
  const api = await init();
  return api.convert_to_base12(BigInt(value));
}

export async function rangeQuery(start, end, count) {
  const api = await init();
  return api.radix_range_iter(BigInt(start), BigInt(end), count);
}

export default init;
